spring:
  application:
    name: catalog-service
  config:
     import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    username: user
    password: password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: refresh